export const products = [
    {
        id: 1,
        title: "Classic Fashionable Men Shoes of Nike",
        color: "Red",
        size: "8",
        material : "",
        rating: 3.8,
        reviews: 1251,
        price: 2500.00,
        img: "images/shoes.jpg",
        quantity: 1,
    },

    {
        id: 2,
        title: "Combo Classic Fashionable Men T-Shirt of Pepe",
        color: "Black, Blue, Shadow",
        size: "M",
        material : "",
        rating: 4.0,
        reviews: 7801,
        price: 500.00,
        img: "images/shirt.jpg",
        quantity: 3,
    },

    {
        id: 3,
        title: "Parker vector Standard Trim Ball Pen",
        color: "Blue",
        size: "",
        material : "ABS Plastic",
        rating: 4.8,
        reviews: 7801,
        price: 1275.00,
        img: "images/pen.jpg",
        quantity: 3,
    },
];